"""add_custom_name

Revision ID: 14fbe859c37a
Revises: 0006_add_github_context_path
Create Date: 2026-06-02 10:33:15.947869
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '14fbe859c37a'
down_revision: Union[str, None] = '0006_add_github_context_path'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('custom_name', sa.String(length=63), nullable=True))
    op.create_unique_constraint('uq_user_custom_name', 'deployments', ['user_id', 'custom_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_custom_name', 'deployments', type_='unique')
    op.drop_column('deployments', 'custom_name')
    # ### end Alembic commands ###
